"""Generate the Swift count-codec frequency constants from the shared QEM tables.

This is a developer fixture generator, never a runtime encoding path. Native
Swift initializes its tables on the GPU from these acquisition-independent
constants; Python uploads the same ``count_tables``. Regeneration must
produce an unchanged file for the existing codec.
"""

from pathlib import Path

from quantem.gpu.formats.qem.reference import count_tables

root = Path(__file__).resolve().parents[1]
source = root / "src/quantem/gpu/resident/mps"
encoding, _ = count_tables()
lines = ["  " + ", ".join(str(int(value >> 16)) for value in row) + "," for row in encoding]
header = """// Fixed count-codec frequencies. Generated by tests/generate_native_count_constants.py.
// These constants are shared with the existing CUDA/MPS model; no data is inspected.
#include <metal_stdlib>
using namespace metal;
constant ushort count_frequencies[64][33] = {
"""
rows = ["  {" + line.strip().rstrip(",") + "}," for line in lines]
kernel = """
};
kernel void count_tables(device uint* encoding [[buffer(0)]],
                         device uint* decoding [[buffer(1)]],
                         uint model [[thread_position_in_grid]]) {
  if (model >= 64) return;
  uint first = 0;
  for (uint symbol = 0; symbol < 33; ++symbol) {
    uint frequency = count_frequencies[model][symbol];
    encoding[model * 33 + symbol] = (frequency << 16) | first;
    for (uint slot = first; slot < first + frequency; ++slot)
      decoding[model * 1024 + slot] = (frequency << 16) | (first << 6) | symbol;
    first += frequency;
  }
}
"""
(source / "kernels/count_tables.msl").write_text(header + "\n".join(rows) + kernel)
