#version 450

layout(local_size_x = 256) in;
layout(set = 0, binding = 0, std430) buffer RowCom { float row_com[]; };
layout(set = 0, binding = 1, std430) buffer ColumnCom { float column_com[]; };
layout(set = 0, binding = 2, std430) readonly buffer Mean { float mean[]; };
layout(push_constant) uniform Parameters { uint scan_count; } parameters;

void main() {
  const uint scan = gl_GlobalInvocationID.x;
  if (scan >= parameters.scan_count) return;
  row_com[scan] -= mean[0];
  column_com[scan] -= mean[1];
}
