"""Compatibility imports for the canonical ``dense`` backend.

New internal callers use the representation-named module. These aliases
retain the same functions/classes without a second implementation.
"""

from .dense import (
    MPSChunked4DSTEM as MPSChunked4DSTEM,
    MPSDecompressor as MPSDecompressor,
    MPSMasterPlan as MPSMasterPlan,
    _ChunkReadPlan as _ChunkReadPlan,
    _MtlArray as _MtlArray,
    _MtlOwner as _MtlOwner,
    __all__ as __all__,
    _bitshuffle_tail_elements as _bitshuffle_tail_elements,
    _buffer_key as _buffer_key,
    _cast_mtl_integer_to_u8 as _cast_mtl_integer_to_u8,
    _check_mps_memory_guard as _check_mps_memory_guard,
    _encode_bitshuffle_tail as _encode_bitshuffle_tail,
    _file_cache_key as _file_cache_key,
    _format_gib as _format_gib,
    _fused_bin_enabled as _fused_bin_enabled,
    _fused_bin_output_tile_shape as _fused_bin_output_tile_shape,
    _fused_bin_pipeline_for as _fused_bin_pipeline_for,
    _fused_full_u16_enabled as _fused_full_u16_enabled,
    _get_cached_decompressor as _get_cached_decompressor,
    _get_chunk_read_plan as _get_chunk_read_plan,
    _get_decompressor as _get_decompressor,
    _make_pipeline as _make_pipeline,
    _max_compressed_bytes_for_plan as _max_compressed_bytes_for_plan,
    _metal_buffer_alloc as _metal_buffer_alloc,
    _mps_max_buffer_bytes as _mps_max_buffer_bytes,
    _mps_output_bytes as _mps_output_bytes,
    _mps_recommended_det_bin as _mps_recommended_det_bin,
    _mps_recommended_working_set_bytes as _mps_recommended_working_set_bytes,
    _mps_skip_memory_check_requested as _mps_skip_memory_check_requested,
    _mtl_array_from_buffer as _mtl_array_from_buffer,
    _normalize_output_dtype as _normalize_output_dtype,
    _numpy_view as _numpy_view,
    _parse_headers as _parse_headers,
    _parse_master_uncached as _parse_master_uncached,
    _raise_if_binned_integer_overflow as _raise_if_binned_integer_overflow,
    _read_pixel_mask as _read_pixel_mask,
    _release_and_raise_if_binned_integer_overflow as _release_and_raise_if_binned_integer_overflow,
    _release_metal_buffer as _release_metal_buffer,
    _release_unique_metal_buffers as _release_unique_metal_buffers,
    clear_mps_cache as clear_mps_cache,
    load_master as load_master,
    load_master_chunked as load_master_chunked,
    load_mps_4dstem as load_mps_4dstem,
    load_prepared_frames as load_prepared_frames,
    plan_master as plan_master,
)
