"""Compatibility imports; canonical implementation: ``quantem.gpu.detector.backends.cuda.kernels``."""

from quantem.gpu.detector.backends.cuda.kernels import (
    _CUDA_VI_CODE as _CUDA_VI_CODE,
    _as_mask_np as _as_mask_np,
    _cuda_screening_sums_exact as _cuda_screening_sums_exact,
    _cuda_vi_module as _cuda_vi_module,
    _flatten_scan as _flatten_scan,
    _flatten_uint4 as _flatten_uint4,
    _scan_shape_from_flat as _scan_shape_from_flat,
    _supported_raw_dtype as _supported_raw_dtype,
    _uint32_accum_safe as _uint32_accum_safe,
    cuda_center_of_mass as cuda_center_of_mass,
    cuda_center_of_mass_uint4 as cuda_center_of_mass_uint4,
    cuda_frame_uint4_to_u8 as cuda_frame_uint4_to_u8,
    cuda_masked_sum as cuda_masked_sum,
    cuda_masked_sum_uint4 as cuda_masked_sum_uint4,
    cuda_mean_dp_uint4 as cuda_mean_dp_uint4,
    cuda_selected_frame_max_uint32 as cuda_selected_frame_max_uint32,
    cuda_selected_frame_max_uint32_uint4 as cuda_selected_frame_max_uint32_uint4,
    cuda_selected_frame_sum_uint64 as cuda_selected_frame_sum_uint64,
    cuda_selected_frame_sum_uint64_uint4 as cuda_selected_frame_sum_uint64_uint4,
    cuda_selected_sum as cuda_selected_sum,
    cuda_selected_sum_from_total as cuda_selected_sum_from_total,
    cuda_selected_sum_from_total_uint4 as cuda_selected_sum_from_total_uint4,
    cuda_selected_sum_uint32 as cuda_selected_sum_uint32,
    cuda_selected_sum_uint4 as cuda_selected_sum_uint4,
    cuda_selected_sum_uint64 as cuda_selected_sum_uint64,
    cuda_sum_all as cuda_sum_all,
    cuda_sum_all_uint64 as cuda_sum_all_uint64,
    cuda_sum_all_uint64_uint4 as cuda_sum_all_uint64_uint4,
)
